begin;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_en text not null,
  name_mk text not null,
  created_at timestamptz not null default now()
);

insert into public.categories (slug, name_en, name_mk)
values
  ('painting', 'Painting', U&'\0421\043B\0438\043A\0430\0440\0441\0442\0432\043E'),
  ('drawing', 'Drawing', U&'\0426\0440\0442\0435\0436'),
  ('digital-art', 'Digital Art', U&'\0414\0438\0433\0438\0442\0430\043B\043D\0430\0020\0443\043C\0435\0442\043D\043E\0441\0442'),
  ('illustration', 'Illustration', U&'\0418\043B\0443\0441\0442\0440\0430\0446\0438\0458\0430'),
  ('mixed-media', 'Mixed Media', U&'\041C\0435\0448\0430\043D\0430\0020\0442\0435\0445\043D\0438\043A\0430'),
  ('photography', 'Photography', U&'\0424\043E\0442\043E\0433\0440\0430\0444\0438\0458\0430'),
  ('other', 'Other', U&'\0414\0440\0443\0433\043E')
on conflict (slug) do nothing;

alter table public.artworks
  add column if not exists title_en text,
  add column if not exists title_mk text,
  add column if not exists description_en text,
  add column if not exists description_mk text,
  add column if not exists category_id bigint references public.categories(id);

update public.artworks
set
  title_en = coalesce(title_en, title),
  description_en = coalesce(description_en, description)
where title_en is null
   or description_en is null;

update public.artworks a
set category_id = c.id
from public.categories c
where a.category_id is null
  and lower(coalesce(a.category, '')) = lower(c.name_en);

create index if not exists idx_artworks_category_id on public.artworks(category_id);

commit;
